spring.application.name=RideBookingApplication
server.servlet.context-path=/ride-booking-service
server.port=8700

# DB configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/RIDEBOOKING
spring.datasource.username=postgres
spring.datasource.password=admindoc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

jwt.secretkey=YOUR_JWT_SECRET

weather.apikey=YOUR_WEATHER_API_KEY

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true